### PR TITLE
NOISSUE - Add comparing docs in CI

### LINKED ISSUE #37: Fix README
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

README should be rephrased to explain the SDK nicer (a bit better phrasing) and use Markdown formatting and links correctly.

Also, docs [`index.md`](https://github.com/mainflux/sdk-py/blob/main/docs/index.md) should probably contain links (if possible to be generated), and API reference link on README should probably lead directly to this `index.md`.

Also - it looks like Markdown is not well generated - Methods are in verbatim, and so Markdown on function names is not applied.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have

### PR DESCRIPTION
**Pull request by 0x6f736f646f**
Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>

### What does this do?
It adds a CI pipeline to check if the docs are in sync or not

### Which issue(s) does this PR fix/relate to?
This issue resolves #37.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
N/A

### Did you document any new/modified functionality?
Done [here](https://github.com/mainflux/sdk-py/pull/36#issuecomment-1013141784)

### Notes
With reference to #36

### CODE REVIEW

**Comment by 0x6f736f646f** [comment]
Let's check it after reviewing #35

**Comment by drasko** [comment]
@0x6f736f646f CI is failing

**Comment by 0x6f736f646f** [comment]
@dusanb94 I am using lazydocs and it isn't available for python version 3.5 as indicated by the test errors [here](https://github.com/mainflux/sdk-py/runs/4842454598?check_suite_focus=true)

We have two options:
- Do away with lazydocs and remain with the initial docs generator
- Use lazydocs and drop support for python version 3.5

Keep in mind lazydocs is able to do Source Code Linking as indicated [here](https://github.com/0x6f736f646f/sdk-py/blob/0x6f-apidocs/docs/channels.md#method-create_bulk)

**Comment by dusanb94** [comment]
> @dusanb94 I am using lazydocs and it isn't available for python version 3.5 as indicated by the test errors [here](https://github.com/mainflux/sdk-py/runs/4842454598?check_suite_focus=true)
> 
> We have two options:
> 
> * Do away with lazydocs and remain with the initial docs generator
> * Use lazydocs and drop support for python version 3.5
> 
> Keep in mind lazydocs is able to do Source Code Linking as indicated [here](https://github.com/0x6f736f646f/sdk-py/blob/0x6f-apidocs/docs/channels.md#method-create_bulk)

@0x6f736f646f Is it possible to check docs in a separate job, not for each test env? We only need it to keep docs up to date, so we don't have to generate docs for each OS and Python version, really.

**Comment by 0x6f736f646f** [comment]
> > @dusanb94 I am using lazydocs and it isn't available for python version 3.5 as indicated by the test errors [here](https://github.com/mainflux/sdk-py/runs/4842454598?check_suite_focus=true)
> > We have two options:
> > 
> > * Do away with lazydocs and remain with the initial docs generator
> > * Use lazydocs and drop support for python version 3.5
> > 
> > Keep in mind lazydocs is able to do Source Code Linking as indicated [here](https://github.com/0x6f736f646f/sdk-py/blob/0x6f-apidocs/docs/channels.md#method-create_bulk)
> 
> @0x6f736f646f Is it possible to check docs in a separate job, not for each test env? We only need it to keep docs up to date, so we don't have to generate docs for each OS and Python version, really.

Yes it is possible

**Comment by 0x6f736f646f** [comment]
Resolves #37

**Review by dusanb94 — APPROVED** [review]

**Review by dusanb94 — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
