### PR TITLE
NOISSUE - Add check acess by key

### PR DESCRIPTION
**Pull request by 0x6f736f646f**
Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>

### What does this do?
It  adss check acess by key

### Which issue(s) does this PR fix/relate to?
It doesn't relate to previous issues

### List any changes that modify/break current functionality
There was no check access by key previously

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
No

### CODE REVIEW

**Comment by drasko** [comment]
Same as [here](https://github.com/mainflux/sdk-py/pull/9#pullrequestreview-848083241)

**Comment by dusanb94** [comment]
> Same as [here](https://github.com/mainflux/sdk-py/pull/9#pullrequestreview-848083241)

Unlike [here](https://github.com/mainflux/sdk-py/pull/9#issuecomment-1011937192) I am also not sure if this is necessary. The idea of the thing key is to provide access control to things, not to perform this kind of "search" by key and access other thing data based on that.

**Comment by drasko** [comment]
@dusanb94 I think this can be helpful if you are buiding backend Pyton-based microservice (like for example some protocol adapter), so that you can communicate Auth service.

**Comment by drasko** [comment]
@0x6f736f646f please resolve conflicts and update the branch

**Comment by 0x6f736f646f** [comment]
Resolved but still, there is some CI errors

**Review by drasko — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
@0x6f736f646f please fix the conflicts and CI

**Pull request merged**
